### ISSUE TITLE
fonttools has changed maintainer and repository

### ISSUE THREAD

**Issue by Pomax** [graphicore/ufoJS#62]
filed as issue rather than as PR, since I don't know what form you'd like the change to be in: fonttools is maintained by @behdad these days, over on https://github.com/behdad/fonttools, rather than being worked on by Just over on the old sourceforge location.

**Comment by graphicore** [comment]
This is a good one. I think a simple edit of the wrong/old information would suffice. I could adapt the gh-pages entry myself then. If you like to see more now, I won't hold you back.

In the longer scope I'll finish the port (essentially UFOReader/Writer are still missing) and then make a v1.0.0 tag release for that  the README could get a more serious overhaul.

**Comment by Pomax** [comment]
PR filed as https://github.com/graphicore/ufoJS/pull/63
